### PR TITLE
Fix branch

### LINKED ISSUE #80: Show current XRP and Euro balance in navbar and accounts page

### PR DESCRIPTION
**Pull request by tomdevman**
**UPDATES:**
This PR addresses a number of fixes related to payments (and payment validations) as well as email notifications. Moreover, the XRP/EUR balance of a user is now displayed in the navbar.

**ISSUES:**
closes #80

### CODE REVIEW

File: src/controllers/UserController.ts [hunk 1]
```diff
@@ -120,4 +122,23 @@ export class UserController {
...
+    @Get("/ticker")
+    async getBalance(): Promise<object> {
+      const url = "https://cex.io/api/ticker/XRP/EUR/";
+      const params = {
+        headers: {
+          "content-type": "application/json; charset=UTF-8"
+        },
+        method: "GET"
+      };
+      const res = await (await fetch(url, params)).json();
```
Comment (roemba) [inline src/controllers/UserController.ts]: Please inline stuff like this

File: src/controllers/LoginController.ts [hunk 2]
```diff
@@ -1,8 +1,9 @@
 import {Container} from "typedi";
-import {Authorized, BadRequestError, Controller, Get, QueryParam} from "routing-controllers";
+import {Authorized, BadRequestError, Controller, Get, QueryParam, CurrentUser} from "routing-controllers";
 import {UserService} from "../services/UserService";
```
Comment (roemba) [inline src/controllers/LoginController.ts]: Import is not used, please clean

File: src/controllers/LoginController.ts [hunk 3]
```diff
@@ -1,8 +1,9 @@
...
 import {ChallengeRepository} from "../repositories/ChallengeRepository";
 import { LoggerService } from "../services/LoggerService";
+import { User } from "../models/User";
```
Comment (roemba) [inline src/controllers/LoginController.ts]: Import is not used, please clean

File: src/events/GeneralScript.ts [hunk 4]
```diff
@@ -0,0 +1,39 @@
+import {Container} from "typedi";
+import {LoggerService} from "../services/LoggerService";
+
+async function getBalances(): Promise<string[]> {
+
+	const balances = [];
+	const ticker = await (await fetch("/api/users/ticker")).json();
+	const info = await (await fetch("/api/users/info")).json();
```
Comment (roemba) [inline src/events/GeneralScript.ts]: Does not work if the user is not logged in

**Review by roemba — CHANGES_REQUESTED** [review]
Besides the above feedback, please merge GeneralScript and NavUpdater as they are both loaded on every page.

**Review by roemba — APPROVED** [review]
